layout: stacked
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
  linkedin: rajita-pujare-a5806b16a
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: software development
    #web_url: https://github.com/topics/css
    image_url: https://www.pngmart.com/files/3/Software-PNG-Transparent-Picture.png

  - name: product management
    image_url: https://www.grenadabroadcast.com/wp-content/uploads/2019/07/CELL-PHONE.png

  - name: machine learning
    #web_url: https://github.com/topics/sass
    image_url: https://webstockreview.net/images/clipart-brain-transparent-background-4.jpg
